// <auto-generated />
namespace AirPro.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class APD1812 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(APD1812));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061809111_APD-1812"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
