// <auto-generated />
namespace AirPro.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201606190732379_v2_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
