namespace AirPro.Entities.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class v299 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("Access.UserClaims", "UserId", "Access.Users");
            DropForeignKey("Access.UserLogins", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserRoles", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Groups", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.GroupRoles", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.GroupRoles", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Groups", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Accounts", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Accounts", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Logins", "UserGuid", "Access.Users");
            DropForeignKey("Support.NotificationTemplates", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Support.NotificationTemplates", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "PaymentVoidByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.PaymentTransactions", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "InvoicedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Orders", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Requests", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "CompletedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "InvoicedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "ResponsibleTechnicianUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.ReportsArchive", "CompletedByUserGuid", "Access.Users");
            DropForeignKey("Scan.ReportsArchive", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.ReportsArchive", "InvoicedByUserGuid", "Access.Users");
            DropForeignKey("Scan.ReportsArchive", "ResponsibleTechnicianUserGuid", "Access.Users");
            DropForeignKey("Scan.ReportsArchive", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.RequestTypes", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.RequestTypes", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.UploadXmls", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.UploadXmls", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Requests", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Orders", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.PaymentTransactions", "PaymentTransactionVoidByUserGuid", "Access.Users");
            DropForeignKey("Billing.PaymentTransactions", "UpdatedByUserGuid", "Access.Users");
            DropPrimaryKey("Access.Users");
            AlterColumn("Access.Users", "UserGuid", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newsequentialid()"));
            AddPrimaryKey("Access.Users", "UserGuid");
            AddForeignKey("Access.UserClaims", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserLogins", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserRoles", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserAccounts", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserGroups", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserShops", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.Logins", "UserGuid", "Access.Users", "UserGuid", cascadeDelete: true);
            AddForeignKey("Access.UserGroups", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Groups", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.GroupRoles", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.GroupRoles", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Groups", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserGroups", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserShops", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserShops", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserAccounts", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserAccounts", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Accounts", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Accounts", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Support.NotificationTemplates", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Support.NotificationTemplates", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "PaymentVoidByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "InvoicedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Orders", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Requests", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "CompletedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "InvoicedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "ResponsibleTechnicianUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.ReportsArchive", "CompletedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.ReportsArchive", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.ReportsArchive", "InvoicedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.ReportsArchive", "ResponsibleTechnicianUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.ReportsArchive", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.RequestTypes", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.RequestTypes", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.UploadXmls", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.UploadXmls", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Requests", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Orders", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "PaymentTransactionVoidByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "UpdatedByUserGuid", "Access.Users", "UserGuid");
        }
        
        public override void Down()
        {
            DropForeignKey("Billing.PaymentTransactions", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.PaymentTransactions", "PaymentTransactionVoidByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Orders", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Requests", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.UploadXmls", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.UploadXmls", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.RequestTypes", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.RequestTypes", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "ResponsibleTechnicianUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "InvoicedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Reports", "CompletedByUserGuid", "Access.Users");
            DropForeignKey("Scan.Requests", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Orders", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "InvoicedByUserGuid", "Access.Users");
            DropForeignKey("Repair.Invoices", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.PaymentTransactions", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "PaymentVoidByUserGuid", "Access.Users");
            DropForeignKey("Billing.Payments", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Support.NotificationTemplates", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Support.NotificationTemplates", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Logins", "UserGuid", "Access.Users");
            DropForeignKey("Access.Accounts", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Accounts", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserShops", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Groups", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.GroupRoles", "UpdatedByUserGuid", "Access.Users");
            DropForeignKey("Access.GroupRoles", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.Groups", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserGroups", "CreatedByUserGuid", "Access.Users");
            DropForeignKey("Access.UserAccounts", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserRoles", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserLogins", "UserGuid", "Access.Users");
            DropForeignKey("Access.UserClaims", "UserGuid", "Access.Users");
            DropPrimaryKey("Access.Users");
            AlterColumn("Access.Users", "UserGuid", c => c.Guid(nullable: false));
            AddPrimaryKey("Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "PaymentTransactionVoidByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Orders", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Requests", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.UploadXmls", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.UploadXmls", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.RequestTypes", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.RequestTypes", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "ResponsibleTechnicianUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "InvoicedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Reports", "CompletedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Scan.Requests", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Orders", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "InvoicedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Repair.Invoices", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.PaymentTransactions", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "PaymentVoidByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Billing.Payments", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Support.NotificationTemplates", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Support.NotificationTemplates", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Logins", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Accounts", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Accounts", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserAccounts", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserAccounts", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserShops", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserShops", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserShops", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserGroups", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserGroups", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Groups", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.GroupRoles", "UpdatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.GroupRoles", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.Groups", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserGroups", "CreatedByUserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserAccounts", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserRoles", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserLogins", "UserGuid", "Access.Users", "UserGuid");
            AddForeignKey("Access.UserClaims", "UserGuid", "Access.Users", "UserGuid");
        }
    }
}
