// <auto-generated />
namespace AirPro.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class APD1445 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(APD1445));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241656536_APD-1445"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
