// <auto-generated />
namespace AirPro.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class APD901 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(APD901));
        
        string IMigrationMetadata.Id
        {
            get { return "201805311636480_APD-901"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
